import React from 'react';
import { QuickActionsGrid } from './QuickActionsGrid';
import {
  Calendar,
  BookOpen,
  GraduationCap,
  Award,
  FileText,
  MessageSquare,
  Camera,
  Video,
  CalendarDays,
  Mail,
  Users,
  TrendingUp
} from 'lucide-react-native';

export const ParentQuickActions: React.FC = () => {
  const parentActions = [
    {
      id: 'attendance',
      title: 'Child Attendance',
      subtitle: 'View attendance records',
      icon: Calendar,
      color: '#3b82f6',
      route: 'AcademicsTab',
      params: { screen: 'Attendance' },
    },
    {
      id: 'timetable',
      title: 'Class Timetable',
      subtitle: 'View class schedule',  
      icon: GraduationCap,
      color: '#10b981',
      route: 'AcademicsTab',
      params: { screen: 'Timetable' },
    },
    {
      id: 'homework',
      title: 'Homework',
      subtitle: 'Check assignments',
      icon: BookOpen,
      color: '#f59e0b',
      route: 'AcademicsTab',
      params: { screen: 'Homework' },
    },
    {
      id: 'exams',
      title: 'Exams & Results',
      subtitle: 'View exam results',
      icon: Award,
      color: '#8b5cf6',
      route: 'AcademicsTab',
      params: { screen: 'Exams' },
    },
    {
      id: 'reports',
      title: 'Report Cards',
      subtitle: 'Academic progress',
      icon: FileText,
      color: '#ef4444',
      route: 'AcademicsTab',
      params: { screen: 'Reports' },
    },
    {
      id: 'online-classes',
      title: 'Online Classes',
      subtitle: 'Join virtual classes',
      icon: Video,
      color: '#e11d48',
      route: 'AcademicsTab',
      params: { screen: 'OnlineClasses' },
    },
    {
      id: 'announcements',
      title: 'Announcements',
      subtitle: 'School updates',
      icon: MessageSquare,
      color: '#059669',
      route: 'MessagesTab',
      params: { screen: 'Announcements' },
    },
    {
      id: 'community',
      title: 'Community',
      subtitle: 'School community',
      icon: Users,
      color: '#0ea5e9',
      route: 'MessagesTab',
      params: { screen: 'Community' },
    },
    {
      id: 'feedback',
      title: 'Feedback',
      subtitle: 'Submit feedback',
      icon: Mail,
      color: '#f97316',
      route: 'MessagesTab',
      params: { screen: 'Feedback' },
    },
    {
      id: 'calendar',
      title: 'Academic Calendar',
      subtitle: 'School events',
      icon: CalendarDays,
      color: '#06b6d4',
      route: 'MessagesTab',
      params: { screen: 'Calendar' },
    },
    {
      id: 'gallery',
      title: 'Gallery',
      subtitle: 'School photos',
      icon: Camera,
      color: '#84cc16',
      route: 'MediaTab',
      params: { screen: 'Gallery' },
    },
    {
      id: 'analytics',
      title: 'Analytics',
      subtitle: 'Performance insights',
      icon: TrendingUp,
      color: '#7c3aed',
      route: 'DashboardTab',
      params: { screen: 'Analytics' },
    },
  ];

  return <QuickActionsGrid actions={parentActions} columns={3} />;
}; 