import React from 'react';
import { QuickActionsGrid } from './QuickActionsGrid';
import {
  Users,
  Calendar,
  BookOpen,
  PenTool,
  Award,
  ClipboardList,
  MessageSquare,
  Camera,
  Video,
  FileText,
  GraduationCap,
  Mail,
  BarChart3
} from 'lucide-react-native';

export const TeacherQuickActions: React.FC = () => {
  const teacherActions = [
    {
      id: 'attendance',
      title: 'Take Attendance',
      subtitle: 'Mark student attendance',
      icon: Users,
      color: '#3b82f6',
      route: 'AttendanceTab',
    },
    {
      id: 'timetable',
      title: 'My Timetable',
      subtitle: 'View class schedule',
      icon: Calendar,
      color: '#10b981',
      route: 'AcademicsTab',
      params: { screen: 'Timetable' },
    },
    {
      id: 'homework',
      title: 'Homework',
      subtitle: 'Assign & manage homework',
      icon: BookOpen,
      color: '#f59e0b',
      route: 'AcademicsTab',
      params: { screen: 'Homework' },
    },
    {
      id: 'marks',
      title: 'Marks Entry',
      subtitle: 'Enter student marks',
      icon: PenTool,
      color: '#8b5cf6',
      route: 'AcademicsTab',
      params: { screen: 'Marks' },
    },
    {
      id: 'exams',
      title: 'Exams',
      subtitle: 'Manage examinations',
      icon: Award,
      color: '#ef4444',
      route: 'AcademicsTab',
      params: { screen: 'Exams' },
    },
    {
      id: 'co-scholastic',
      title: 'Co-Scholastic',
      subtitle: 'Assess activities',
      icon: GraduationCap,
      color: '#06b6d4',
      route: 'AcademicsTab',
      params: { screen: 'CoScholastic' },
    },
    {
      id: 'online-classes',
      title: 'Online Classes',
      subtitle: 'Schedule virtual classes',
      icon: Video,
      color: '#e11d48',
      route: 'AcademicsTab',
      params: { screen: 'OnlineClasses' },
    },
    {
      id: 'leave-requests',
      title: 'Leave Requests',
      subtitle: 'Apply for leave',
      icon: FileText,
      color: '#7c3aed',
      route: 'AcademicsTab',
      params: { screen: 'LeaveRequests' },
    },
    {
      id: 'announcements',
      title: 'Announcements',
      subtitle: 'Post announcements',
      icon: MessageSquare,
      color: '#059669',
      route: 'MessagesTab',
      params: { screen: 'Announcements' },
    },
    {
      id: 'community',
      title: 'Community',
      subtitle: 'School community',
      icon: Mail,
      color: '#0ea5e9',
      route: 'MessagesTab',
      params: { screen: 'Community' },
    },
    {
      id: 'feedback',
      title: 'Feedback',
      subtitle: 'View feedback',
      icon: MessageSquare,
      color: '#f97316',
      route: 'MessagesTab',
      params: { screen: 'Feedback' },
    },
    {
      id: 'gallery',
      title: 'Gallery',
      subtitle: 'Manage photos',
      icon: Camera,
      color: '#84cc16',
      route: 'GalleryTab',
    },
  ];

  return <QuickActionsGrid actions={teacherActions} columns={3} />;
}; 